FROM apache/superset:6.1.0

# Всё делаем от root
USER root

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        libpq-dev build-essential python3-pip && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# 1) ставим pip внутрь venv от root
RUN /app/.venv/bin/python -m ensurepip --upgrade || true && \
    /app/.venv/bin/python -m pip install --upgrade pip

# 2) ставим нужные пакеты в тот же venv
RUN /app/.venv/bin/python -m pip install --no-cache-dir psycopg2-binary clickhouse-connect

# И только теперь переключаемся на пользователя superset
USER superset
